### PR TITLE
Added optional key to useAlgoliaRecommend

### PR DESCRIPTION
**Pull request by LoMonacoSalvatore**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Multiple useAlgoliaRecommend calls would overwrite the 'recommend-result' useState. Added an optional key param to make it unique composable

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Review by Baroshem — COMMENTED** [review]
On recommendation for better Developer Experience IMO :)

**Comment by Baroshem** [comment]
Hey @LoMonacoSalvatore 

Thank you so much for this PR. I have added a small recommendation to your code that could make the DX a bit better :)

**Comment by LoMonacoSalvatore** [comment]
@Baroshem looks way better! Thank you for your change!

**Comment by Archetipo95** [comment]
@Baroshem This is a very useful fix, I'm experiencing the same problem with algolia in my project and I think that this will solve it!

**Comment by Baroshem** [comment]
Hey folks, 

Sorry I had an emergency yesterday. I am merging the code and will release it with the next version soon :)

**Comment by Baroshem** [comment]
Release with 1.9.0 version :)

**Pull request merged**
