### PR TITLE
docs: using vue-instantsearch with ssr

### PR DESCRIPTION
**Pull request by Laruxo**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Adds documentation on using vue-instantsearch with SSR in Nuxt 3.

Resolve https://github.com/nuxt-modules/algolia/issues/132

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by Baroshem** [comment]
Hey @Laruxo 

Could you add here the recommendations from Haroenv? I would like to merge this PR to the upcoming 1.6.0 version of the module :)

**Comment by Laruxo** [comment]
After the comment from Haroenv, I found that this solution only works for very simple cases. I am still debugging to understand how to make it work with refinements and initial UI state.

**Comment by Baroshem** [comment]
Ok, thanks for the heads up! I will await further docs section then.

Kudos to you! 🍪

**Comment by Laruxo** [comment]
@Baroshem this is the latest working version. I don't like how it looks, but I hope that somebody with more Vue/Nuxt knowledge will find a better alternative soon.

**Comment by Baroshem** [comment]
Hey @Laruxo 

Thank you very much for the documentation about it!

I think for now we can have this intruction on how to use Instantsearch with Nuxt on SSR.

**Pull request merged**
