### PR TITLE
Add option to enable requester-fetch instead of requester-node-http for edge-environments like Cloudflare Workers

### PR DESCRIPTION
**Pull request by vilhelmjosander**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
This PR enables support for using this module in edge-environments which usually does not have access to nodes http module. Examples would be Cloudflare Workers or Vercel Edge (https://vercel.com/docs/functions/edge-functions/edge-runtime). By enabling `useFetch` in the configuration it will use @algolia/requester-fetch instead of @algolia/requester-node-http when process.server is true.

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by Baroshem** [comment]
Hey, thanks for this PR!

I will take a look at it soon :)

**Review by Baroshem — APPROVED** [review]
Everything good! Thanks for making this PR. Really nice work.

I wont be merging this PR yet As I would like to release a big new version soon 2.0.0 and this PR would fit right in there :)

**Comment by vilhelmjosander** [comment]
Any updates on when 2.0.0 will be released? There is no way this can be merged as a minor version until then?

**Comment by Baroshem** [comment]
Hey @vilhelmjosander 

I am planning to release the 2.0.0 next week. I was just very busy with Nuxt Security 1.0.0 release for the Nuxt Nation that is happening just know. 

If I wont make it to release 2.0.0 version next week, then I will release a minor version with this feature so that you could start using it :)

**Comment by Baroshem** [comment]
Hey @vilhelmjosander 

I have changed the base branch from main to 1.10.0 and I want to release it this week. Could you please resolve the conflicts and remove the additional package-lock.json? 

Then I will merge it and release a new version with it :)

**Comment by vilhelmjosander** [comment]
@Baroshem Sorry for the late reply. I have fixed the merge conflicts and removed the package-lock.json. Make sure it looks ok then it should be reade to merge and release.

**Comment by Baroshem** [comment]
@vilhelmjosander I will work on making the release today then.

Thanks for your work!

**Review by Baroshem — APPROVED** [review]

**Pull request merged**
